version: "3"
services:
  nginx:
    image: ${REGISTRY_ADDRESS}/nginx:${IMAGE_TAG}
    restart: always
    depends_on:
      - php-fpm
    ports:
      - "80:80"
  php-fpm:
    image: ${REGISTRY_ADDRESS}/php-fpm:${IMAGE_TAG}
    restart: always
    environment:
      APP_SECRET: ${APP_SECRET}
    depends_on:
      - postgres
  php-cli:
    image: ${REGISTRY_ADDRESS}/php-cli:${IMAGE_TAG}
    restart: always
    environment:
      APP_SECRET: ${APP_SECRET}
    depends_on:
      - postgres
  postgres:
    image: ${REGISTRY_ADDRESS}/postgres:${IMAGE_TAG}
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: app

volumes:
  postgres: