version: '3'
services:
  nginx:
    build:
      context: ./.docker/nginx/development
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
  php-fpm:
    build:
      context: ./.docker/php-fpm/development
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - postgres
  php-cli:
    build:
      context: ./.docker/php-cli/development
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    depends_on:
      - postgres
  postgres:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    ports:
      - "15432:5432"

volumes:
  composer:
  postgres:
